language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codecov

script:
  - pytest tests --cov alphavantage --cov tests -s

after_success:
  - codecov